name: CI/CD

on: [ 'push' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: lint, test, build
        run: |
          make lint
          make test
          make build
